<?php
session_start();
require_once __DIR__ . '/config/config.php';

// Check if form is submitted
if (isset($_POST['register'])) {
    $id_number   = trim($_POST['id_number']);
    
    // Convert names to UPPERCASE
    $first_name  = strtoupper(trim($_POST['first_name']));
    $middle_name = strtoupper(trim($_POST['middle_name']));
    $last_name   = strtoupper(trim($_POST['last_name']));
    
    $full_name   = trim($first_name . ' ' . ($middle_name ? $middle_name . ' ' : '') . $last_name);
    $username    = trim($_POST['username']); // Generated by JS, but captured here
    $user_type   = trim($_POST['user_type']);
    $password_plain = trim($_POST['password']);
    $password = password_hash($password_plain, PASSWORD_DEFAULT);
    $created_at  = date('Y-m-d H:i:s');

    // Basic validation
    $errors = [];
    if (!$id_number) $errors[] = "ID number is required.";
    if (!$first_name || !$last_name) $errors[] = "First and last name are required.";
    if (!$username) $errors[] = "Username is required.";
    if (!$password_plain) $errors[] = "Password is required.";
    if (!$user_type) $errors[] = "User type is required.";

    // Check if username already exists
    $stmt = $conn->prepare("SELECT id FROM fs_reports.qcl_user WHERE username = ?");
    $stmt->bind_param("s", $username);
    $stmt->execute();
    $stmt->store_result();
    if ($stmt->num_rows > 0) $errors[] = "Username already exists.";
    $stmt->close();

    if (empty($errors)) {
        $stmt = $conn->prepare("
            INSERT INTO fs_reports.qcl_user 
            (id_number, first_name, middle_name, last_name, full_name, username, user_type, password, created_at) 
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ");
        $stmt->bind_param(
            "sssssssss",
            $id_number, $first_name, $middle_name, $last_name, $full_name, $username, $user_type, $password, $created_at
        );

        if ($stmt->execute()) {
            $_SESSION['success'] = "User registered successfully!";
            header("Location: login.php");
            exit;
        } else {
            $errors[] = "Database error: " . $stmt->error;
        }
        $stmt->close();
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Register</title>
<link rel="icon" href="images/MLW%20Logo.png" type="image/png"/>

<style>
    body { font-family: Arial, sans-serif; background: #f2f4f7; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; }
    .register-container { background: #fff; padding: 30px 40px; border-radius: 10px; box-shadow: 0 8px 20px rgba(0,0,0,0.1); width: 400px; }
    h2 { text-align: center; margin-bottom: 25px; color: #333; }
    label { display: block; margin-bottom: 5px; font-weight: bold; color: #555; }
    input[type="text"], input[type="password"], select { width: 100%; padding: 10px 12px; margin-bottom: 20px; border: 1px solid #ccc; border-radius: 5px; font-size: 14px; box-sizing: border-box; }
    input[readonly] { background-color: #eee; cursor: not-allowed; }
    button { width: 100%; padding: 12px; background: #ff0000; border: none; color: #fff; font-size: 16px; font-weight: bold; border-radius: 5px; cursor: pointer; transition: background 0.3s ease; }
    button:hover { background: #a60000; }
    .errors { background: #ffe6e6; color: #cc0000; padding: 10px; margin-bottom: 20px; border-radius: 5px; }
    .success { background: #e6ffe6; color: #006600; padding: 10px; margin-bottom: 20px; border-radius: 5px; }

    .password-wrapper {
    position: relative;
    width: 100%;
}

.password-wrapper input {
    padding-right: 40px; /* Make room for the icon */
}

.toggle-password {
    position: absolute;
    right: 10px;
    top: 10px;
    cursor: pointer;
    color: #555;
    font-size: 18px;
    user-select: none;
}

</style>
</head>
<body>

<div class="register-container">
<h2>Register New User</h2>

<?php
if (!empty($errors)) {
    echo "<div class='errors'><ul>";
    foreach ($errors as $e) echo "<li>$e</li>";
    echo "</ul></div>";
}
if (isset($_SESSION['success'])) {
    echo "<div class='success'>" . $_SESSION['success'] . "</div>";
    unset($_SESSION['success']);
}
?>

<form method="post">
    <label>ID Number:</label>
    <input type="text" name="id_number" id="id_number" required>

    <label>First Name:</label>
    <input type="text" name="first_name" style="text-transform: uppercase;" required>

    <label>Middle Name:</label>
    <input type="text" name="middle_name" style="text-transform: uppercase;">

    <label>Last Name:</label>
    <input type="text" name="last_name" id="last_name" style="text-transform: uppercase;" required>

    <label>Username (Auto-generated):</label>
    <input type="text" name="username" id="username" readonly>

    <label>Password:</label>
<div class="password-wrapper">
    <input type="password" name="password" id="password" value='Mlinc1234' required>
    <span class="toggle-password" id="togglePassword">👁️</span>
</div>

    <label>User Type:</label>
    <select name="user_type" required>
        <option value="">Select Type</option>
        <option value="admin">Admin</option>
        <option value="user">User</option>
        <option value="bookkeeper">Bookkeeper</option>
        <option value="reports">Reports</option>
    </select>

    <button type="submit" name="register">Register</button>
</form>
</div>

<script>
    const idInput = document.getElementById('id_number');
    const lastInput = document.getElementById('last_name');
    const userInput = document.getElementById('username');

    function generateUsername() {
        let lastName = lastInput.value.trim().toUpperCase();
        let idNumber = idInput.value.trim();
        
        // Get first 4 letters of last name
        let lastPart = lastName.substring(0, 4);
        
        if (lastPart && idNumber) {
            userInput.value = lastPart + idNumber;
        } else {
            userInput.value = '';
        }
    }

    // Listen for typing in either field
    idInput.addEventListener('input', generateUsername);
    lastInput.addEventListener('input', generateUsername);


    const passwordInput = document.getElementById('password');
const togglePassword = document.getElementById('togglePassword');

togglePassword.addEventListener('click', function () {
    // Toggle the type attribute
    const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
    passwordInput.setAttribute('type', type);
    
    // Toggle the eye icon (optional: change icon look) 
    this.textContent = type === 'password' ? '👁️' : '🙈';
});
</script>


</body>
</html>